# 演示配置文件 - 启用多种输出格式
# 这个配置文件展示了如何同时启用多种格式

# ================== 文件格式控制 ==================
formats:
  # 启用TXT文件
  enable_txt: true
  
  # 启用EPUB电子书
  enable_epub: true
  
  # 启用HTML和LaTeX格式  
  enable_html: true
  enable_latex: true
  
  # 启用PDF生成（需要安装pdflatex）
  enable_pdf: false

# ================== 目录配置 ==================
directories:
  # JSON文件存储目录（必须有）
  bookstore_dir: "demo_downloads/bookstore"
  
  # 其他格式文件存储目录
  download_dir: "demo_downloads/files"

# ================== 下载性能配置 ==================
performance:
  # 使用较少线程数进行演示
  thread_count: 4
  
  # 使用快速模式（演示用）
  delay_mode: "fast"

# ================== 文件管理配置 ==================
file_management:
  # 合成TXT后删除章节文件夹（演示清理功能）
  delete_chapters_after_merge: true
  
  # 遇到冲突时重命名
  conflict_resolution: "rename"

# ================== Cookie和认证配置 ==================
authentication:
  # 自动生成Cookie
  cookie_mode: "auto"
  
  # 跳过Cookie验证（加快启动速度）
  validate_cookie: false

# ================== 日志配置 ==================
logging:
  # 详细输出模式（方便调试）
  level: "verbose"

# ================== 网络配置 ==================
network:
  timeout: 30               # 网络请求超时时间(秒)
  retry_count: 3            # 重试次数
  retry_delays: [1, 2, 4]   # 重试间隔(秒) - 第1次重试等1秒，第2次等2秒，第3次等4秒
  rotate_user_agent: true   # 是否轮换User-Agent

# ================== 高级选项 ==================
advanced:
  enable_experimental: false   # 是否启用实验性功能
  memory_mode: "normal"        # 内存使用模式: low, normal, high
  show_progress_bar: true      # 是否显示进度条 